# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename off
set-option -g mouse on
set-option -g status-position top
source ~/.config/tmux/theme.conf
source ~/.config/tmux/statusline.conf
source ~/.config/tmux/utility.conf

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-pain-control'
run '~/.config/tmux/plugins/tpm/tpm'
